#!/usr/bin/env bash

set -xeuo pipefail

DISK=rustos-uefi.img
SIZE=128M
KERNEL=target/x86_64-unknown-none/debug/blog_os
LIMINE=limine

curl -L -o limine/BOOTX64.EFI https://github.com/limine-bootloader/limine/raw/refs/heads/v9.x-binary/BOOTX64.EFI
curl -L -o limine/limine.sys https://github.com/limine-bootloader/limine/raw/refs/heads/v9.x-binary/limine-bios.sys

# Clean old image
rm -f "$DISK"

# Create FAT32 image (ESP)
truncate -s "$SIZE" "$DISK"
mkfs.vfat -F32 "$DISK"

# Create EFI dirs
mmd -i "$DISK" ::/EFI
mmd -i "$DISK" ::/EFI/BOOT

# Copy Limine bootloader and config
mcopy -i "$DISK" "$LIMINE/BOOTX64.EFI" ::/EFI/BOOT/
mcopy -i "$DISK" "$LIMINE/limine.sys"  ::
mcopy -i "$DISK" "$LIMINE/limine.conf"  ::

# Copy kernel
mcopy -i "$DISK" "$KERNEL" ::blog_os.img

echo "UEFI boot disk created: $DISK"

/usr/libexec/qemu-kvm   -machine q35   -m 256M   -cpu host \
  -drive if=pflash,format=raw,readonly=on,file=/usr/share/edk2/ovmf/OVMF_CODE.fd \
  -drive "format=raw,file=$DISK" -vga std -serial stdio