[package]
name = "rustyk"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.102", default-features = false }
bootloader_api = "0.11.15"
concurrent-queue = { version = "2.5.0", default-features = false }
conquer-once = { version = "0.4.0", default-features = false }
crossbeam-queue = { version = "0.3.12", default-features = false, features = ["alloc"] }
embedded-graphics = "0.8.1"
futures-util = { version = "0.3.32", default-features = false, features = ["alloc"] }
linked_list_allocator = "0.10.5"
nostd = "0.1.5"
pc-keyboard = "0.8.0"
pic8259 = "0.11.0"
pin-project-lite = { version = "0.2.17", default-features = false }
qemu-exit = "3.0.2"
spin = "0.10.0"
vga = "0.2.9"
volatile = "0.2.6"
x86_64 = "0.15.2"

[dependencies.lazy_static]
version = "1.5.0"
features = ["spin_no_std"]

[[bin]]
name = "test_heap_allocation"

[[bin]]
name = "test_stack_overflow"


[features]
default = []
with-self-tests = []
tracing = []
