[build]
#target = "x86_64-unknown-none"
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-C", "panic=abort",
  "-Z", "panic_abort_tests"
]

[unstable]
build-std = ["core", "alloc"]
build-std-features = []

